[workspace]
members = [
    "crates/fairing-core",
    "crates/git-repositories",
    "crates/scylla-repositories",
    "fairing",
    "fairing-acme",
    "fairing-core",
    "fairing-proto",
    "fairingctl",
]

[profile.release]
lto = "fat"
