[package]
name = "fairing"
version = "0.1.0"
authors = ["Martin Risell Lilja <martin.risell.lilja@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.13"
bytes = "1"
clap = "2"
fairing-core = { path = "../fairing-core" }
fairing-proto = { path = "../fairing-proto" }
futures = "0.3"
hyper = "0.14"
nom = "6"
sqlx = { version = "0.5", features = ["postgres", "uuid", "chrono", "runtime-tokio-rustls"] }
thrussh = "0.32"
thrussh-keys = "0.20"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread", "sync"] }
tonic = { git = "https://github.com/hyperium/tonic" }
tonic-web = { git = "https://github.com/hyperium/tonic" }
tracing = "0.1"
tracing-subscriber = "0.2"
uuid = { version = "0.8", features = ["v4"] }
